"""Criar  tabela categorias e produtos

Revision ID: dde615cce1d4
Revises: 3b235b2a84ed
Create Date: 2026-06-01 09:58:19.595714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde615cce1d4'
down_revision: Union[str, Sequence[str], None] = '3b235b2a84ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
